### ISSUE TITLE
String Problem - Solve 

### ISSUE THREAD

**Issue by fl-la** [Alabamajack/Garfield#22]
solving string problem 
possible solution :
- [ ] creating own namespace, e.g. garfield_string or so
- [ ] implementing own string class
- [ ] implementing required string operation functions like to_string

Alternative:
solve problem in finding the problem in NIOS II eclipse and know how to program "around" the problem

**Comment by Litschi** [comment]
ALTERA support does recommend using external memory, this is due to their C++ support. All C++ applications need minimum about 700KByte. This leads to the follow restrictions while using C++:
    1) do _NOT_ use any of the C++ headers (ALTERAs implementations are the main problem for the memory footprint)
   2) all other zero cost mechanisms (like classes) and all built in types that are also available in C are usable
